[[protocols]]
name = "korbox"
protocol = "nec"
[protocols.scancodes]
0x645b = "KEY_OK"
0x640f = "KEY_POWER"
0x644d = "KEY_UP"
0x645a = "KEY_DOWN"
0x6417 = "KEY_1"
0x641b = "KEY_2"
0x641f = "KEY_3"
0x6416 = "KEY_4" 
0x641a = "KEY_5"
0x641e = "KEY_6"
0x6415 = "KEY_7"
0x6419 = "KEY_8"
0x641d = "KEY_9"
0x6418 = "KEY_0"
0x6411 = "KEY_RED"
0x6412 = "KEY_GREEN"
0x6413 = "KEY_YELLOW"
0x6450 = "KEY_BLUE"
